// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsPortal.Data;

#nullable disable

namespace SportsPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107080524_AddTeamCategory")]
    partial class AddTeamCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsPortal.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("AdminID");

                    b.ToTable("tbl_AdminUsers");
                });

            modelBuilder.Entity("SportsPortal.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnnouncementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementID"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Message");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PostedDate");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Priority");

                    b.HasKey("AnnouncementID");

                    b.ToTable("tbl_Announcements");
                });

            modelBuilder.Entity("SportsPortal.Models.Department", b =>
                {
                    b.Property<int>("DeptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptID"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DeptName");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LogoUrl");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("TotalPoints");

                    b.HasKey("DeptID");

                    b.ToTable("tbl_Departments");
                });

            modelBuilder.Entity("SportsPortal.Models.GalleryImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ImageID");

                    b.ToTable("tbl_GalleryImages");
                });

            modelBuilder.Entity("SportsPortal.Models.Match", b =>
                {
                    b.Property<int>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchID"));

                    b.Property<int?>("DeptA_ID")
                        .HasColumnType("int")
                        .HasColumnName("DeptA_ID");

                    b.Property<int?>("DeptB_ID")
                        .HasColumnType("int")
                        .HasColumnName("DeptB_ID");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MatchDate");

                    b.Property<string>("ScoreA")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ScoreA");

                    b.Property<string>("ScoreB")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ScoreB");

                    b.Property<int>("SeasonID")
                        .HasColumnType("int")
                        .HasColumnName("SeasonID");

                    b.Property<int>("SportID")
                        .HasColumnType("int")
                        .HasColumnName("SportID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("MatchID");

                    b.HasIndex("DeptA_ID");

                    b.HasIndex("DeptB_ID");

                    b.HasIndex("SeasonID");

                    b.HasIndex("SportID");

                    b.ToTable("tbl_Matches");
                });

            modelBuilder.Entity("SportsPortal.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<int>("DeptID")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit")
                        .HasColumnName("IsCaptain");

                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RegNumber");

                    b.Property<int>("SportID")
                        .HasColumnType("int")
                        .HasColumnName("SportID");

                    b.HasKey("PlayerID");

                    b.HasIndex("DeptID");

                    b.HasIndex("SportID");

                    b.ToTable("tbl_Players");
                });

            modelBuilder.Entity("SportsPortal.Models.Season", b =>
                {
                    b.Property<int>("SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeasonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.HasKey("SeasonID");

                    b.ToTable("tbl_Seasons");
                });

            modelBuilder.Entity("SportsPortal.Models.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportID"));

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SportName");

                    b.HasKey("SportID");

                    b.ToTable("tbl_Sports");
                });

            modelBuilder.Entity("SportsPortal.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<int>("DeptID")
                        .HasColumnType("int")
                        .HasColumnName("DeptID");

                    b.Property<int>("SportID")
                        .HasColumnType("int")
                        .HasColumnName("SportID");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamID");

                    b.HasIndex("DeptID");

                    b.HasIndex("SportID");

                    b.ToTable("tbl_Teams");
                });

            modelBuilder.Entity("SportsPortal.Models.Match", b =>
                {
                    b.HasOne("SportsPortal.Models.Department", "DepartmentA")
                        .WithMany()
                        .HasForeignKey("DeptA_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsPortal.Models.Department", "DepartmentB")
                        .WithMany()
                        .HasForeignKey("DeptB_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsPortal.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsPortal.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentA");

                    b.Navigation("DepartmentB");

                    b.Navigation("Season");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsPortal.Models.Player", b =>
                {
                    b.HasOne("SportsPortal.Models.Department", "Department")
                        .WithMany("Players")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsPortal.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsPortal.Models.Team", b =>
                {
                    b.HasOne("SportsPortal.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsPortal.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsPortal.Models.Department", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
